import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { teams, updateNotes } from "@/lib/game-data";
import { useColors } from "@/hooks/use-colors";

export default function LeagueScreen() {
  const colors = useColors();
  const ranking = [...teams].sort((a, b) => b.wins - a.wins);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.muted }]}>CAMPEONATO NACIONAL</Text><Text style={[styles.title, { color: colors.foreground }]}>Central da Liga</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Acompanhe a temporada e as notas de balanceamento do universo fictício.</Text><View style={[styles.updateCard, { backgroundColor: colors.primary }]}><View style={styles.updateIcon}><IconSymbol name="arrow.triangle.2.circlepath" size={22} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.updateKicker}>ÚLTIMA ATUALIZAÇÃO</Text><Text style={styles.updateTitle}>Temporada de Meio de Ano</Text><Text style={styles.updateText}>Ajustes defensivos, novos talentos e desafio da rodada já disponíveis.</Text></View></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Classificação</Text><View style={[styles.table, { backgroundColor: colors.surface, borderColor: colors.border }]}>{ranking.map((team, index) => <View key={team.id} style={styles.tableRow}><Text style={[styles.position, { color: index === 0 ? "#FFD166" : colors.muted }]}>{String(index + 1).padStart(2, "0")}</Text><View style={[styles.dot, { backgroundColor: team.color }]} /><Text style={[styles.team, { color: colors.foreground }]}>{team.name}</Text><Text style={[styles.record, { color: colors.muted }]}>{team.wins}-{team.losses}</Text><Text style={[styles.power, { color: colors.foreground }]}>{team.power}</Text></View>)}</View><Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 22 }]}>Notas da rodada</Text>{updateNotes.map((note, index) => <View key={note.title} style={[styles.note, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.noteIcon, { backgroundColor: index === 0 ? "#103A32" : "#2B253D" }]}><IconSymbol name={index === 0 ? "shield" as any : "star.fill"} size={19} color={index === 0 ? colors.success : "#FFD166"} /></View><View style={{ flex: 1 }}><Text style={[styles.noteTitle, { color: colors.foreground }]}>{note.title}</Text><Text style={[styles.noteText, { color: colors.muted }]}>{note.text}</Text></View></View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 35 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 18 }, updateCard: { borderRadius: 20, padding: 16, flexDirection: "row", gap: 13, alignItems: "flex-start", marginBottom: 23 }, updateIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.18)", alignItems: "center", justifyContent: "center" }, updateKicker: { color: "rgba(255,255,255,0.7)", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, updateTitle: { color: "#FFFFFF", fontSize: 17, fontWeight: "900", marginTop: 4 }, updateText: { color: "rgba(255,255,255,0.78)", fontSize: 11, lineHeight: 16, marginTop: 4 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 10 }, table: { borderWidth: 1, borderRadius: 18, paddingVertical: 6 }, tableRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 13, paddingVertical: 12, gap: 9 }, position: { width: 22, fontSize: 11, fontWeight: "900" }, dot: { width: 9, height: 9, borderRadius: 5 }, team: { flex: 1, fontSize: 12, fontWeight: "800" }, record: { fontSize: 11, width: 38, textAlign: "right" }, power: { fontSize: 12, fontWeight: "900", width: 28, textAlign: "right" }, note: { borderWidth: 1, borderRadius: 17, padding: 13, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 9 }, noteIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, noteTitle: { fontSize: 13, fontWeight: "900" }, noteText: { fontSize: 11, lineHeight: 16, marginTop: 3 } });
