import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";

export default function MoreScreen() {
  const colors = useColors();
  const [trained, setTrained] = useState(false);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.muted }]}>CENTRAL DO TÉCNICO</Text><Text style={[styles.title, { color: colors.foreground }]}>Mais opções</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Prepare o clube para o próximo desafio.</Text><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Treinamento da semana</Text><View style={[styles.trainingCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.trainingIcon, { backgroundColor: "#103A32" }]}><IconSymbol name="bolt.fill" size={20} color={colors.success} /></View><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{trained ? "Treino concluído" : "Defesa e entrosamento"}</Text><Text style={[styles.cardText, { color: colors.muted }]}>{trained ? "Seu elenco ganhou confiança para a próxima partida." : "Aumenta a defesa do time e recupera um pouco de moral."}</Text></View><Pressable onPress={() => setTrained(true)} style={({ pressed }) => [styles.smallButton, { backgroundColor: trained ? colors.border : colors.primary }, pressed && { opacity: 0.75 }]}><Text style={styles.smallButtonText}>{trained ? "Feito" : "Treinar"}</Text></Pressable></View><Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 22 }]}>Atalhos</Text>{[{ title: "Mercado de atletas", copy: "Busque novas peças para sua rotação", icon: "person.fill", color: "#2B253D" }, { title: "Categorias de base", copy: "Descubra a próxima promessa brasileira", icon: "star.fill", color: "#40361E" }, { title: "Configurações", copy: "Preferências, acessibilidade e dados locais", icon: "gearshape.fill", color: "#173042" }].map((item) => <Pressable key={item.title} style={({ pressed }) => [styles.menuRow, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.78 }]}><View style={[styles.menuIcon, { backgroundColor: item.color }]}><IconSymbol name={item.icon as any} size={20} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={[styles.menuTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.menuCopy, { color: colors.muted }]}>{item.copy}</Text></View><IconSymbol name="chevron.right" size={21} color={colors.muted} /></Pressable>)}<View style={[styles.footerCard, { borderColor: colors.border }]}><Text style={[styles.footerTitle, { color: colors.foreground }]}>Cesta Nacional Mobile</Text><Text style={[styles.footerText, { color: colors.muted }]}>Protótipo de gestão esportiva com clubes e jogadores fictícios. Dados de desempenho servem ao balanceamento do universo do jogo.</Text><Text style={[styles.version, { color: colors.primary }]}>VERSÃO 0.1.0 • ANDROID FIRST</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 36 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 20 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 10 }, trainingCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, trainingIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cardTitle: { fontSize: 13, fontWeight: "900" }, cardText: { fontSize: 11, lineHeight: 16, marginTop: 3 }, smallButton: { paddingHorizontal: 12, paddingVertical: 9, borderRadius: 11 }, smallButtonText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, menuRow: { borderWidth: 1, borderRadius: 17, padding: 13, flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 9 }, menuIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, menuTitle: { fontSize: 13, fontWeight: "900" }, menuCopy: { fontSize: 11, marginTop: 3 }, footerCard: { borderWidth: 1, borderRadius: 17, padding: 15, marginTop: 13 }, footerTitle: { fontSize: 13, fontWeight: "900" }, footerText: { fontSize: 11, lineHeight: 17, marginTop: 5 }, version: { fontSize: 9, fontWeight: "900", letterSpacing: 1, marginTop: 12 } });
