import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { seasonNews } from "@/lib/game-data";
import { useCareer } from "@/lib/career-store";
import { useColors } from "@/hooks/use-colors";

export default function NewsScreen() {
  const colors = useColors();
  const { wins, losses, directorMessage, seasonEnded, seasonAward } = useCareer();
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: colors.muted }]}>UNIVERSO DA LIGA</Text><Text style={[styles.title, { color: colors.foreground }]}>Notícias</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Acompanhe as histórias que dão personalidade à sua temporada.</Text>{seasonEnded && <View style={[styles.finale, { backgroundColor: colors.primary }]}><IconSymbol name="trophy.fill" size={26} color="#FFD166" /><View style={{ flex: 1 }}><Text style={styles.finaleKicker}>TEMPORADA ENCERRADA</Text><Text style={styles.finaleTitle}>{seasonAward}</Text><Text style={styles.finaleText}>Campanha final: {wins} vitórias e {losses} derrotas. Novos objetivos estão prontos para a próxima temporada.</Text></View></View>}<View style={[styles.formCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.formIcon, { backgroundColor: "#103A32" }]}><IconSymbol name="newspaper" size={21} color={colors.success} /></View><View style={{ flex: 1 }}><Text style={[styles.formKicker, { color: colors.success }]}>PLANTÃO DO CLUBE</Text><Text style={[styles.formTitle, { color: colors.foreground }]}>{directorMessage}</Text><Text style={[styles.formText, { color: colors.muted }]}>A diretoria atualiza suas expectativas após cada decisão importante.</Text></View></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Histórico da temporada</Text>{seasonNews.map((news) => <View key={news.title} style={[styles.newsCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.newsBadge, { backgroundColor: news.tone === "win" ? "#103A32" : news.tone === "market" ? "#2B253D" : "#173042" }]}><IconSymbol name={news.tone === "win" ? "trophy.fill" : news.tone === "market" ? "person.fill" : "flag"} size={19} color={news.tone === "win" ? colors.success : news.tone === "market" ? "#FFD166" : colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.newsDay, { color: colors.primary }]}>{news.day}</Text><Text style={[styles.newsTitle, { color: colors.foreground }]}>{news.title}</Text><Text style={[styles.newsText, { color: colors.muted }]}>{news.text}</Text></View></View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 36 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 20 }, finale: { borderRadius: 20, padding: 16, flexDirection: "row", alignItems: "flex-start", gap: 12, marginBottom: 14 }, finaleKicker: { color: "rgba(255,255,255,0.75)", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, finaleTitle: { color: "#FFFFFF", fontSize: 19, fontWeight: "900", marginTop: 3 }, finaleText: { color: "rgba(255,255,255,0.82)", fontSize: 11, lineHeight: 16, marginTop: 4 }, formCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", gap: 11, marginBottom: 22 }, formIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, formKicker: { fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, formTitle: { fontSize: 13, fontWeight: "900", lineHeight: 18, marginTop: 4 }, formText: { fontSize: 10, lineHeight: 15, marginTop: 3 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 10 }, newsCard: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: "row", gap: 12, marginBottom: 9 }, newsBadge: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, newsDay: { fontSize: 9, fontWeight: "900", letterSpacing: 0.8 }, newsTitle: { fontSize: 14, fontWeight: "900", marginTop: 4 }, newsText: { fontSize: 11, lineHeight: 17, marginTop: 4 } });
