import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { type Player } from "@/lib/game-data";
import { useCareer } from "@/lib/career-store";
import { useColors } from "@/hooks/use-colors";

function PlayerRow({ player, selected, onToggle, onOpen }: { player: Player; selected: boolean; onToggle: () => void; onOpen: () => void }) {
  const colors = useColors();
  return <Pressable onPress={onToggle} onLongPress={onOpen} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: selected ? colors.primary : colors.border }, pressed && { opacity: 0.78 }]}><View style={[styles.avatar, { backgroundColor: player.position === "PIVÔ" ? "#FFD166" : "#F47B20" }]}><Text style={styles.avatarText}>{player.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</Text></View><View style={styles.playerInfo}><View style={styles.nameLine}><Text style={[styles.name, { color: colors.foreground }]}>{player.name}</Text>{selected && <Text style={[styles.starter, { color: colors.success }]}>TITULAR</Text>}</View><Text style={[styles.meta, { color: colors.muted }]}>{player.position} • {player.style}</Text><View style={styles.statLine}><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.points}</Text> PTS</Text><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.rebounds}</Text> REB</Text><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.assists}</Text> AST</Text></View></View><View style={styles.rating}><Text style={[styles.ratingNumber, { color: colors.foreground }]}>{player.overall}</Text><Text style={[styles.ratingLabel, { color: colors.muted }]}>OVR</Text><Text style={[styles.detailHint, { color: colors.primary }]}>detalhes</Text></View></Pressable>;
}

function PlayerProfile({ player }: { player: Player }) {
  const colors = useColors();
  const bars = [{ label: "Ataque", value: player.overall }, { label: "Defesa", value: player.defense }, { label: "Energia", value: player.energy }, { label: "Potencial", value: player.potential === "Muito alto" ? 92 : player.potential === "Elite" ? 88 : 80 }];
  return <View style={[styles.profile, { backgroundColor: "#173042", borderColor: colors.primary }]}><View style={styles.profileHeader}><View><Text style={[styles.profileKicker, { color: colors.primary }]}>PERFIL DO ATLETA</Text><Text style={[styles.profileName, { color: colors.foreground }]}>{player.name}</Text><Text style={[styles.profileMeta, { color: colors.muted }]}>#{player.number} • {player.position} • {player.style}</Text></View><Text style={[styles.profileOverall, { color: colors.warning }]}>{player.overall}</Text></View><Text style={[styles.profileSection, { color: colors.foreground }]}>Atributos atuais</Text>{bars.map((bar) => <View key={bar.label} style={styles.barRow}><Text style={[styles.barLabel, { color: colors.muted }]}>{bar.label}</Text><View style={[styles.barTrack, { backgroundColor: colors.border }]}><View style={[styles.barFill, { width: `${bar.value}%`, backgroundColor: bar.label === "Defesa" ? colors.success : colors.primary }]} /></View><Text style={[styles.barValue, { color: colors.foreground }]}>{bar.value}</Text></View>)}<View style={styles.profileStats}><View><Text style={[styles.statBig, { color: colors.foreground }]}>{player.points}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>PONTOS/JOGO</Text></View><View><Text style={[styles.statBig, { color: colors.foreground }]}>{player.rebounds}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>REBOTES/JOGO</Text></View><View><Text style={[styles.statBig, { color: colors.foreground }]}>{player.assists}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>ASSIST./JOGO</Text></View></View><Text style={[styles.history, { color: colors.muted }]}>Forma recente: <Text style={{ color: colors.success, fontWeight: "900" }}>+4.2%</Text> • evolução estimada na próxima atualização.</Text></View>;
}

export default function RosterScreen() {
  const colors = useColors();
  const { roster, starterIds, toggleStarter } = useCareer();
  const [selectedPlayerId, setSelectedPlayerId] = useState<string | null>(null);
  const selectedPlayer = roster.find((player) => player.id === selectedPlayerId);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={roster} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><Text style={[styles.eyebrow, { color: colors.muted }]}>GESTÃO DO TIME</Text><Text style={[styles.title, { color: colors.foreground }]}>Seu elenco</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Toque para definir titular. Mantenha pressionado para abrir o perfil detalhado.</Text><View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>ENTROSAMENTO</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>86%</Text></View><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>ENERGIA MÉDIA</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>89%</Text></View><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>TITULARES</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>{starterIds.length}/5</Text></View></View>{selectedPlayer && <PlayerProfile player={selectedPlayer} />}<Text style={[styles.sectionTitle, { color: colors.foreground }]}>Rotação principal</Text></View>} renderItem={({ item }) => <PlayerRow player={item} selected={starterIds.includes(item.id)} onToggle={() => toggleStarter(item.id)} onOpen={() => setSelectedPlayerId(item.id)} />} ListFooterComponent={<View style={[styles.note, { backgroundColor: "#102B40" }]}><IconSymbol name="star.fill" size={18} color="#FFD166" /><Text style={[styles.noteText, { color: colors.muted }]}>Os dados são fictícios e servem para balanceamento do universo do jogo.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 30, gap: 10 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 18 }, summary: { borderWidth: 1, borderRadius: 18, padding: 16, flexDirection: "row", justifyContent: "space-between", marginBottom: 18 }, summaryLabel: { fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, summaryValue: { fontSize: 23, fontWeight: "900", marginTop: 5 }, profile: { borderWidth: 1, borderRadius: 18, padding: 15, marginBottom: 18 }, profileHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, profileKicker: { fontSize: 9, fontWeight: "900", letterSpacing: 1 }, profileName: { fontSize: 20, fontWeight: "900", marginTop: 4 }, profileMeta: { fontSize: 10, marginTop: 4 }, profileOverall: { fontSize: 30, fontWeight: "900" }, profileSection: { fontSize: 13, fontWeight: "900", marginTop: 15, marginBottom: 9 }, barRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 7 }, barLabel: { width: 52, fontSize: 10 }, barTrack: { flex: 1, height: 6, borderRadius: 4, overflow: "hidden" }, barFill: { height: "100%", borderRadius: 4 }, barValue: { width: 25, fontSize: 10, fontWeight: "900", textAlign: "right" }, profileStats: { flexDirection: "row", justifyContent: "space-between", marginTop: 10, paddingTop: 12, borderTopWidth: 1, borderTopColor: "#23445D" }, statBig: { fontSize: 17, fontWeight: "900" }, statLabel: { fontSize: 8, fontWeight: "800", marginTop: 2 }, history: { fontSize: 10, marginTop: 13 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 2 }, row: { borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 11, minHeight: 83 }, avatar: { width: 47, height: 47, borderRadius: 16, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#071A2B", fontWeight: "900" }, playerInfo: { flex: 1 }, nameLine: { flexDirection: "row", alignItems: "center", gap: 7 }, name: { fontSize: 13, fontWeight: "900" }, starter: { fontSize: 8, fontWeight: "900", letterSpacing: 0.4 }, meta: { fontSize: 10, marginTop: 3 }, statLine: { flexDirection: "row", gap: 9, marginTop: 8 }, stat: { fontSize: 9, fontWeight: "800" }, rating: { alignItems: "center", minWidth: 38 }, ratingNumber: { fontSize: 22, fontWeight: "900" }, ratingLabel: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 }, detailHint: { fontSize: 7, fontWeight: "900", marginTop: 3 }, note: { borderRadius: 15, padding: 14, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 6 }, noteText: { flex: 1, fontSize: 11, lineHeight: 16 } });
