import { useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { players, type Player } from "@/lib/game-data";
import { useColors } from "@/hooks/use-colors";

function PlayerRow({ player, selected, onToggle }: { player: Player; selected: boolean; onToggle: () => void }) {
  const colors = useColors();
  return <Pressable onPress={onToggle} style={({ pressed }) => [styles.row, { backgroundColor: colors.surface, borderColor: selected ? colors.primary : colors.border }, pressed && { opacity: 0.78 }]}><View style={[styles.avatar, { backgroundColor: player.position === "PIVÔ" ? "#FFD166" : "#F47B20" }]}><Text style={styles.avatarText}>{player.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</Text></View><View style={styles.playerInfo}><View style={styles.nameLine}><Text style={[styles.name, { color: colors.foreground }]}>{player.name}</Text>{selected && <Text style={[styles.starter, { color: colors.success }]}>TITULAR</Text>}</View><Text style={[styles.meta, { color: colors.muted }]}>{player.position} • {player.style}</Text><View style={styles.statLine}><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.points}</Text> PTS</Text><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.rebounds}</Text> REB</Text><Text style={[styles.stat, { color: colors.foreground }]}><Text style={{ color: colors.primary, fontWeight: "900" }}>{player.assists}</Text> AST</Text></View></View><View style={styles.rating}><Text style={[styles.ratingNumber, { color: colors.foreground }]}>{player.overall}</Text><Text style={[styles.ratingLabel, { color: colors.muted }]}>OVR</Text></View></Pressable>;
}

export default function RosterScreen() {
  const colors = useColors();
  const [selected, setSelected] = useState(players.filter((player) => player.starter).map((player) => player.id));
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={players} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><Text style={[styles.eyebrow, { color: colors.muted }]}>GESTÃO DO TIME</Text><Text style={[styles.title, { color: colors.foreground }]}>Seu elenco</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Toque em um atleta para ajustar os cinco titulares.</Text><View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>ENTROSAMENTO</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>86%</Text></View><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>ENERGIA MÉDIA</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>89%</Text></View><View><Text style={[styles.summaryLabel, { color: colors.muted }]}>TITULARES</Text><Text style={[styles.summaryValue, { color: colors.foreground }]}>{selected.length}/5</Text></View></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Rotação principal</Text></View>} renderItem={({ item }) => <PlayerRow player={item} selected={selected.includes(item.id)} onToggle={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : current.length < 5 ? [...current, item.id] : current)} />} ListFooterComponent={<View style={[styles.note, { backgroundColor: "#102B40" }]}><IconSymbol name="star.fill" size={18} color="#FFD166" /><Text style={[styles.noteText, { color: colors.muted }]}>Dados de desempenho são fictícios e servem para balanceamento do universo do jogo.</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 30, gap: 10 }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.3 }, title: { fontSize: 30, fontWeight: "900", marginTop: 4 }, subtitle: { fontSize: 13, lineHeight: 19, marginTop: 5, marginBottom: 18 }, summary: { borderWidth: 1, borderRadius: 18, padding: 16, flexDirection: "row", justifyContent: "space-between", marginBottom: 22 }, summaryLabel: { fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, summaryValue: { fontSize: 23, fontWeight: "900", marginTop: 5 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginBottom: 2 }, row: { borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 11, minHeight: 83 }, avatar: { width: 47, height: 47, borderRadius: 16, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#071A2B", fontWeight: "900" }, playerInfo: { flex: 1 }, nameLine: { flexDirection: "row", alignItems: "center", gap: 7 }, name: { fontSize: 13, fontWeight: "900" }, starter: { fontSize: 8, fontWeight: "900", letterSpacing: 0.4 }, meta: { fontSize: 10, marginTop: 3 }, statLine: { flexDirection: "row", gap: 9, marginTop: 8 }, stat: { fontSize: 9, fontWeight: "800" }, rating: { alignItems: "center", minWidth: 34 }, ratingNumber: { fontSize: 22, fontWeight: "900" }, ratingLabel: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 }, note: { borderRadius: 15, padding: 14, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 6 }, noteText: { flex: 1, fontSize: 11, lineHeight: 16 } });
